version: '3.9'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile

        container_name: CourseHunt-frontend-app
        image: CourseHunt-frontend-

        restart: always

        ports:
            - "3000:3000"

        environment:
            NODE_ENV: production

        command: [ "npm", "run", "start" ]

        volumes:
            - .:/app
